### ISSUE TITLE
NGS (genomic DNA) analyses using Galaxy

### ISSUE THREAD

**Issue by Tsaaki1** [ScienceParkStudyGroup/studyGroup#12]
Hi,

I am using Galaxy to analyze my sequencing data. Ultimately I want to see SNPs in the sequenced genome. I was able to generate mapping on the reference genome in the BAM format. But I am stuck here. The next thing would be Variant calling. When I perform this step, I cannot properly view these SNPs.
Does anyone have a workflow for this kind of analyses and willing to share?

My workflow is essentially: 
1. Get Data
2. FastQC on  1 
3. MultiQC  2
4. NGS: QC and manipulation, Trimmomatic on 1 
5. FastQC on 4 
6. MultiQC on 5 
7. Mapping: Bowtie2 on 4 
8.

**Comment by mgalland** [comment]
Hello Terence, 
Seems like you're the first to post a real issue here (and not a lesson). 
We sure can help. If you're willing to wait a little bit (10 days), we will plan so-called "hacky hour" where you can come to solve issues like this one. In the past, we had an irregular number of people joining these "hacky hours". Thus, now, what I'm planning to do is to ask at workshop sessions (next one on November 21) how many people would like to join the following week hacky hour.  Then, we'll know how many people actually come. 
I don't have Galaxy workflows (I'm interested though to see how you use it) but rather I have workflows made with Snakemake. 
Please, come to the next Study Group sessions (November 21th) as we will see how many people 
Best,
Marc
Ps: did you search on Biostars or Seqanswers forums?

**Comment by Tsaaki1** [comment]
@mgalland thank you for comments. I will definitely come to the next session. In the meantime, I will go through your suggestions. I have not go through Biostars and SeqAnwers. 

regards,
Terrens

**Comment by mgalland** [comment]
Hey Terence, 
Any update on this?
